name: Unit Tests

on:
  push:
  pull_request:

permissions:
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build and Run Tests
      run: ./gradlew test
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v5
      if: success() || failure() # always run even if the previous step fails
      with:
        fail_on_failure: true
        report_paths: '**/build/test-results/test/TEST-*.xml'
