name: Unit Tests

on:
  push:
  pull_request:

permissions:
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build and run tests
      run: ./gradlew test
    - name: Publish test report
      uses: mikepenz/action-junit-report@v5
      if: success() || failure() # always run even if the previous step fails
      with:
        fail_on_failure: true
        report_paths: '**/build/test-results/test/TEST-*.xml'
    - name: Upload test reports
      uses: actions/upload-artifact@v4
      with:
        name: Test reports
        path: '**/build/test-results/test/TEST-*.xml'
        if-no-files-found: warn
        retention-days: 30
        overwrite: true
